#!/usr/bin/env python
"""Generate RoboCasa Diffusion Policy task configs for the P2C camera ablation.

PLAN.md section 7.2 says to *prepare but not launch* the remote Diffusion Policy runs, and
PLAN.md section 5 says the downstream policy should stay deliberately conventional so
policy novelty does not confound the contribution.

That turns out to need no code change at all: the upstream task config declares its
cameras in ``shape_meta.obs``, so a camera subset is produced by removing entries. This
script does that transformation on the upstream file rather than hand-copying it, so the
generated configs track upstream (image shapes, state keys, action keys, env_runner
settings) instead of drifting from a snapshot.

Generated, mapping onto the baselines of PLAN.md section 12:

    B0_primary          single third-person view   (partial observation)
    B2_primary_wrist    third-person + wrist       (fixed complementary pair)
    B3_all_views        all three cameras          (full-view oracle)

B4 (primary + *random* second view) is deliberately **not** generated: a static
``shape_meta`` cannot express a per-sample random camera choice, so B4 needs a small
change on the dataset side. See ``--help`` output and the note printed at the end.

Usage::

    python scripts/make_dp_configs.py \
        --upstream external/diffusion_policy/diffusion_policy/config/task/robocasa/target_atomic_seen.yaml \
        --out configs/diffusion_policy
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Camera subsets, expressed as the observation keys to KEEP from shape_meta.obs.
# Names match the real keys verified in the RoboCasa365 datasets.
SUBSETS = {
    "B0_primary": {
        "cameras": ["robot0_agentview_left_image"],
        "note": "B0 partial observation: one third-person view",
    },
    "B1_wrist": {
        "cameras": ["robot0_eye_in_hand_image"],
        "note": "B1 alternative single view: wrist only",
    },
    "B2_primary_wrist": {
        "cameras": ["robot0_agentview_left_image", "robot0_eye_in_hand_image"],
        "note": "B2 fixed complementary pair: third-person + wrist",
    },
    "B2b_primary_secondary": {
        "cameras": ["robot0_agentview_left_image", "robot0_agentview_right_image"],
        "note": "fixed third-person pair, to separate 'a second view' from 'a wrist view'",
    },
    "B3_all_views": {
        "cameras": [
            "robot0_agentview_left_image",
            "robot0_agentview_right_image",
            "robot0_eye_in_hand_image",
        ],
        "note": "B3 full-view oracle: the dataset's upper bound",
    },
    "CD_primary_duplicate": {
        "cameras": ["robot0_agentview_left_image"],
        "duplicate": True,
        "note": "duplicate control: the same camera twice. Needs the duplicate entry to point at "
                "the same lerobot key; verify the dataset loader accepts that.",
    },
}

HEADER = """# GENERATED by scripts/make_dp_configs.py -- do not edit by hand.
#
# Source: {src}
# Subset: {name} ({ncam} camera(s))
#   {note}
#
# Only shape_meta.obs differs from the upstream config. Everything else -- image shapes,
# state keys, action keys, env_runner and dataset settings -- is upstream's, so these
# arms differ only in which camera streams the policy sees (the harness contract
# (docs/harness_contract.md)).
#
# NOT YET RUN. These configs were written against upstream but have not been executed:
# this machine has a 4 GB GPU and the official guidance is >=24 GB for training. Before
# the first remote run, check at least:
#   * dataset.dataset_soup -- upstream points at a multi-task soup; PLAN.md section 7.2
#     says to start with ONE task, so this likely needs a single-task soup entry.
#   * env_runner.dataset_path -- upstream hard-codes a cluster path that will not exist.
#   * dataloader.batch_size -- upstream uses 192; adjust for the actual GPU and record
#     the effective batch size (PLAN.md section 7.2).
#   * that the policy's observation encoder accepts the reduced camera count.
"""


def extract_obs_keys(text: str) -> list[str]:
    """Observation keys declared under shape_meta.obs, in file order."""
    lines = text.splitlines()
    start = None
    for i, ln in enumerate(lines):
        if re.match(r"^\s*obs:\s*$", ln):
            start = i
            break
    if start is None:
        raise ValueError("could not find 'obs:' under shape_meta in the upstream config")
    base_indent = len(lines[start]) - len(lines[start].lstrip())
    keys = []
    for ln in lines[start + 1 :]:
        if not ln.strip() or ln.strip().startswith("#"):
            continue
        indent = len(ln) - len(ln.lstrip())
        if indent <= base_indent:
            break
        if indent == base_indent + 2 and ln.rstrip().endswith(":"):
            keys.append(ln.strip().rstrip(":"))
    return keys


def filter_obs_block(text: str, keep: list[str], duplicate: bool = False) -> str:
    """Return the config with shape_meta.obs reduced to ``keep``.

    Non-image observations (state, language) are always kept: the ablation is about camera
    streams, and changing the proprioception would confound it.
    """
    lines = text.splitlines()
    start = next(i for i, ln in enumerate(lines) if re.match(r"^\s*obs:\s*$", ln))
    base_indent = len(lines[start]) - len(lines[start].lstrip())

    out = lines[: start + 1]
    i = start + 1
    current_key: str | None = None
    buffer: list[str] = []
    kept_blocks: dict[str, list[str]] = {}
    order: list[str] = []

    def flush():
        nonlocal buffer, current_key
        if current_key is not None:
            kept_blocks[current_key] = buffer
            order.append(current_key)
        buffer = []

    while i < len(lines):
        ln = lines[i]
        if ln.strip() and (len(ln) - len(ln.lstrip())) <= base_indent:
            break
        if ln.strip() and (len(ln) - len(ln.lstrip())) == base_indent + 2 and ln.rstrip().endswith(":"):
            flush()
            current_key = ln.strip().rstrip(":")
            buffer = [ln]
        else:
            buffer.append(ln)
        i += 1
    flush()
    tail = lines[i:]

    for key in order:
        is_image = key.endswith("_image")
        if is_image and key not in keep:
            continue
        out.extend(kept_blocks[key])
        if duplicate and is_image:
            # A second slot carrying the same camera. Renaming the key while keeping the
            # same lerobot_keys is what makes this a duplicate control, not a real pair.
            dup = [
                ln.replace(key, f"{key}_dup", 1) if ln.strip().startswith(key) else ln
                for ln in kept_blocks[key]
            ]
            out.extend(dup)

    return "\n".join(out + tail) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--upstream", type=str,
        default="external/diffusion_policy/diffusion_policy/config/task/robocasa/"
                "target_atomic_seen.yaml",
    )
    p.add_argument("--out", type=str, default="configs/diffusion_policy")
    p.add_argument("--subsets", type=str, nargs="+", default=None,
                   help=f"which to generate (default: all of {list(SUBSETS)})")
    args = p.parse_args()

    root = Path(__file__).resolve().parents[1]
    src = Path(args.upstream)
    if not src.is_absolute():
        src = root / src
    if not src.exists():
        print(f"error: upstream config not found at {src}", file=sys.stderr)
        print("Clone it first:", file=sys.stderr)
        print("  git clone https://github.com/robocasa-benchmark/diffusion_policy.git "
              "external/diffusion_policy", file=sys.stderr)
        return 2

    text = src.read_text()
    declared = extract_obs_keys(text)
    images = [k for k in declared if k.endswith("_image")]
    print(f"upstream: {src}")
    print(f"observation keys : {declared}")
    print(f"camera keys      : {images}")
    print()

    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = root / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    names = args.subsets or list(SUBSETS)
    written = []
    for name in names:
        spec = SUBSETS.get(name)
        if spec is None:
            print(f"skip unknown subset '{name}'", file=sys.stderr)
            continue
        unknown = [c for c in spec["cameras"] if c not in images]
        if unknown:
            print(f"skip '{name}': upstream has no camera(s) {unknown}", file=sys.stderr)
            continue

        body = filter_obs_block(text, spec["cameras"], spec.get("duplicate", False))
        header = HEADER.format(
            src=src.relative_to(root) if src.is_relative_to(root) else src,
            name=name, ncam=len(spec["cameras"]), note=spec["note"],
        )
        # Keep upstream's `name:` field distinct per arm so runs are distinguishable.
        body = re.sub(r"^name:\s*(\S+)", rf"name: \1_p2c_{name}", body, count=1,
                      flags=re.M)
        dest = out_dir / f"p2c_{name}.yaml"
        dest.write_text(header + "\n" + body)
        written.append(dest)
        print(f"wrote {dest.relative_to(root)}  ({len(spec['cameras'])} camera(s))")

    print()
    print("NOTE: B4 (primary + random second view) is not generated. A static shape_meta")
    print("cannot express a per-sample random camera, so B4 needs a change on the dataset")
    print("side of diffusion_policy -- e.g. a wrapper that swaps which lerobot video key")
    print("feeds the second image slot per sample. The local tiny-BC ablation already")
    print("covers B4 (condition 'random_two'), so run that first: PLAN.md section 7.2 says")
    print("to scale to the remote stage only if the local result is meaningful.")
    print()
    print(f"generated {len(written)} config(s). None has been run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
